# Generated by Django 4.2.14 on 2024-07-26 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('rent_deposit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('body_type', models.CharField(choices=[('седан', 'седан'), ('хэтчбек', 'хэтчбек'), ('универсал', 'универсал'), ('купе', 'купе'), ('кабриолет', 'кабриолет'), ('родстер', 'родстер'), ('внедорожник', 'внедорожник'), ('пикап', 'пикап'), ('минивэн', 'минивэн'), ('фургон', 'фургон'), ('лимузин', 'лимузин'), ('микроавтобус', 'микроавтобус'), ('грузовик', 'грузовик')], default='седан', max_length=64)),
                ('drive_unit', models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('4WD', '4WD')], max_length=32)),
                ('fuel', models.CharField(choices=[('дизель', 'дизель'), ('бензин', 'бензин'), ('гибрид', 'гибрид'), ('электро', 'электро'), ('водород', 'водород')], max_length=32)),
                ('car_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1971)])),
                ('engine_power', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transmission', models.CharField(choices=[('АКПП', 'АКПП'), ('МКПП', 'МКПП'), ('Вариатор', 'Вариатор'), ('Робот', 'Робот')], max_length=32)),
                ('description', models.TextField()),
                ('car_number', models.CharField(max_length=64)),
                ('car_photo', models.URLField(max_length=256)),
                ('car_status', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
