# Generated by Django 4.2.14 on 2024-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('седан', 'седан'), ('хэтчбек', 'хэтчбек'), ('универсал', 'универсал'), ('купе', 'купе'), ('кабриолет', 'кабриолет'), ('родстер', 'родстер'), ('внедорожник', 'внедорожник'), ('пикап', 'пикап'), ('минивэн', 'минивэн'), ('фургон', 'фургон'), ('лимузин', 'лимузин'), ('микроавтобус', 'микроавтобус')], default='седан', max_length=64),
        ),
    ]
