# Generated by Django 4.2.14 on 2024-08-03 04:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_body_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-time_create'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_create'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('седан', 'седан'), ('хэтчбек', 'хэтчбек'), ('универсал', 'универсал'), ('купе', 'купе'), ('кабриолет', 'кабриолет'), ('родстер', 'родстер'), ('внедорожник', 'внедорожник'), ('пикап', 'пикап'), ('минивэн', 'минивэн'), ('фургон', 'фургон'), ('лимузин', 'лимузин'), ('микроавтобус', 'микроавтобус')], max_length=64, verbose_name='body_type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=64, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=64, verbose_name='car_number'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(upload_to='media/car_photos/', verbose_name='car_photo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.BooleanField(default=True, verbose_name='car_status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1971)], verbose_name='car_year'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('4WD', '4WD')], max_length=32, verbose_name='drive_unit'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='engine_power'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('дизель', 'дизель'), ('бензин', 'бензин'), ('гибрид', 'гибрид'), ('электро', 'электро'), ('водород', 'водород')], max_length=32, verbose_name='fuel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_deposit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='rent_deposit'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('АКПП', 'АКПП'), ('МКПП', 'МКПП'), ('Вариатор', 'Вариатор'), ('Робот', 'Робот')], max_length=32, verbose_name='transmission'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['time_create'], name='idx_time_create'),
        ),
    ]
