# Generated by Django 4.2.14 on 2024-08-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_car_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_create'),
        ),
    ]
